import fs from 'node:fs'
import path from 'node:path'

import { loadProjectConfig } from '../../utils/config'
import { logger } from '../../utils/logger'
import { loadAliasEntries } from '../check/index'
import { buildDependencyGraph } from '../graph/index'
import { generateStats } from '../stats/index'

export interface DocsOptions {
  out?: string
}

export function generateDocs(outPath: string): void {
  const config = loadProjectConfig()
  const srcPath = path.join(process.cwd(), config.srcDir)
  const aliases = loadAliasEntries(process.cwd(), config.srcDir)

  logger.info(`Generating architectural documentation (${config.architecture})...`)

  // 1. Get stats
  const stats = generateStats(srcPath, config.architecture)

  // 2. Get dependency graph
  const mermaidGraph = buildDependencyGraph(srcPath, aliases, { excludeShared: true })

  // 3. Assemble Markdown
  const lines: string[] = []

  lines.push('# Architecture Documentation\n')
  lines.push(
    `This project uses the **${config.architecture.toUpperCase()}** architectural methodology.\n`,
  )

  lines.push('## Project Statistics\n')
  lines.push(`- **Total Managed Files:** ${stats.totalFiles}`)
  const layerCount = Object.keys(stats.layers).filter((l) => l !== 'unknown').length
  lines.push(`- **Layers:** ${layerCount}`)
  const totalSlices = Object.values(stats.layers).reduce((acc, l) => acc + l.slices.size, 0)
  lines.push(`- **Total Slices:** ${totalSlices}\n`)

  lines.push('## Layers Overview\n')
  const FSD_LAYER_ORDER = ['app', 'processes', 'pages', 'widgets', 'features', 'entities', 'shared']
  const layers = Object.keys(stats.layers).sort((a, b) => {
    if (config.architecture === 'fsd') {
      const idxA = FSD_LAYER_ORDER.indexOf(a)
      const idxB = FSD_LAYER_ORDER.indexOf(b)
      if (idxA !== -1 && idxB !== -1) return idxA - idxB
      if (idxA !== -1) return -1
      if (idxB !== -1) return 1
    }
    return a.localeCompare(b)
  })

  for (const layer of layers) {
    if (layer === 'unknown') continue
    const { fileCount, slices } = stats.layers[layer]
    lines.push(`### \`${layer}\``)
    lines.push(`- **Files:** ${fileCount}`)
    if (slices.size > 0) {
      lines.push(`- **Slices (${slices.size}):**`)
      const sortedSlices = Array.from(slices).sort()
      for (const slice of sortedSlices) {
        lines.push(`  - \`${slice}\``)
      }
    } else {
      lines.push(`- **Slices:** None`)
    }
    lines.push('') // empty line
  }

  lines.push('## Dependency Graph\n')
  lines.push(
    'The following graph represents the import dependencies between different architecture slices (excluding `shared` to reduce noise).\n',
  )
  lines.push('```mermaid')
  lines.push(mermaidGraph.trim())
  lines.push('```\n')
  lines.push(
    '---\n_Generated by [component-forge](https://github.com/vladislavprozorov/component-forge)_',
  )

  const finalMd = lines.join('\n')

  fs.mkdirSync(path.dirname(outPath), { recursive: true })
  fs.writeFileSync(outPath, finalMd, 'utf8')

  logger.success(`✓ Documentation successfully written to ${path.relative(process.cwd(), outPath)}`)
}

export function docsCommand(options: DocsOptions = {}): void {
  const outPath = path.resolve(process.cwd(), options.out || 'ARCHITECTURE.md')
  generateDocs(outPath)
}
